### ISSUE TITLE
Translate for spanish is possible

### ISSUE THREAD

**Issue by johnfelipe** [Code4SA/indigo#1]
In transifex, i will translate to spanish

**Comment by longhotsummer** [comment]
If you wish to contribute a translation, that would be great. Please send a pull request when you have one. Thanks!

**Comment by johnfelipe** [comment]
But is possible for u, create in your code multilanguage, and with transifex i will translate to spanish

**Comment by longhotsummer** [comment]
A translated version is not in scope or budget at this point because we don't require it.

**Comment by johnfelipe** [comment]
Show me or teach me how put all for multilanguage feature

**Comment by longhotsummer** [comment]
Why would you like it translated? Are you using the platform?

**Comment by johnfelipe** [comment]
I want it use it
