### ISSUE TITLE
Upgrade Django to 1.10.1

### ISSUE THREAD

**Issue by rkunal** [Code4SA/indigo#26]
Too early to upgrade to Django 1.11 LTS right now. But updating to 1.10.x would help make the upgrade to LTS easier later on.
Have tested Indigo with Django 1.10.1. Will start with this version, and upgrade to 1.10.6 if all things go smooth.
Major concern being the Third Party libraries/plugins.

**Comment by longhotsummer** [comment]
1.10's mainstream support ends in April. Instead, what if we upgraded to 1.8 LTS? That would pave the way to upgrade to 1.11 LTS once that's out. I'd rather steer clear of non-LTS releases.

For context: we're currently on 1.7 which expired on 1 December 2015. https://www.djangoproject.com/download/

**Comment by rkunal** [comment]
I get the rationale behind sticking with LTS. 
My concern is that it is not possible to support something that we ourselves don't use on a production system.

**Comment by longhotsummer** [comment]
What will you do with your production systems when support for 1.10 ends next month? Maybe if we wait long enough 1.11 will come out and solve this :)

**Comment by longhotsummer** [comment]
I've started this process.

Upgrading to Django 1.8 in https://github.com/Code4SA/indigo/tree/django-1.8

**Comment by longhotsummer** [comment]
1.8 was straight-forward. Moving to 1.9 will be a bit bigger, because other libraries must be updated too (eg. django-reversion).

**Comment by rkunal** [comment]
Django did bring in some major changes in 1.9 and 1.10, which forced libraries to change their apis a bit.

**Comment by longhotsummer** [comment]
I'm making some progress in the 1.9 branch. I don't think it'll be much more work. 

Greg
--
(iPhone)
